### ISSUE TITLE
Launching console text editor hangs console.

### ISSUE THREAD

**Issue by yurikus** [terrajobst/git-istage#33]
repro:
- Configure core.editor with an editor that runs in text mode in the same console. I used Far Manager and FTE 
- Stage changes, press C, git-istage launches `git commit -v`, which launches `sh ...{edtior}` which appears hung. It's unable to write to the same console?

**Comment by terrajobst** [comment]
Hmm, interesting. I don't even know whether that's possible.

**Comment by yurikus** [comment]
git spawns a new conhost, which makes the editor invisible:

![image](https://user-images.githubusercontent.com/11010776/98165345-5d63e200-1eab-11eb-936e-a4b02c9c4032.png)


fte: https://github.com/tenox7/ntutils/tree/master/fte

**Comment by terrajobst** [comment]
In case anyone cares what the fix was:

* In .NET you can generally launch a CLI from a CLI process just fine; the new process will use the same terminal, that is read from its input and write to its output.
* However, this means that the process shouldn't be launched with redirecting output if you intend for it to be visible... duh. In my case, I generally do that when launching Git in order to its error log. For commands that Git will spawn the editor for, that's not a good idea.
* Lastly, when using alternative screen buffers you want to swap bag to the main screen buffer too.

**Comment by terrajobst** [comment]
@yurikus, a new version (v0.3.93) was being published to NuGet. It'll probably take 30-60 min before it will show up though.

**Comment by yurikus** [comment]
Can we roll to back to net6 lts for target framework?

**Comment by terrajobst** [comment]
Why? What's the issue with installing it? It's fully side-by-side.

**Comment by yurikus** [comment]
Want to be on the LTS of net core. Net7 might not be available on all the hosts I'm using this on. This desire for latest and greatest without real need is a bit misguided IMHO.

**Comment by yurikus** [comment]
@terrajobst Here's why:
```
$ apt search dotnet-sdk
Sorting... Done
Full Text Search... Done
dotnet-sdk-6.0/jammy-updates,now 6.0.111-0ubuntu1~22.04.1 amd64 [installed]
  dotNET 6.0 Software Development Kit

dotnet-sdk-6.0-source-built-artifacts/jammy-updates 6.0.111-0ubuntu1~22.04.1 amd64
  Internal package for building dotNet 6.0 Software Development Kit


yurikus@ubnt-docker ~
$ dotnet tool install git-istage -g
/tmp/b64b4635-d55c-4c58-8b0f-a4b14ad7812a/restore.csproj : error NU1202: 
Package git-istage 0.3.93 is not compatible with net6.0 (.NETCoreApp,Version=v6.0) / any. 
Package git-istage 0.3.93 supports: net7.0 (.NETCoreApp,Version=v7.0) / any
The tool package could not be restored.
```

**Comment by yurikus** [comment]
Your answer is above 😁
Ubuntu doesn't have readily installable net7 sdk

**Comment by terrajobst** [comment]
> Your answer is above 😁

Sorry, I meant I ask folks at Microsoft why that's missing :-)

**Comment by yurikus** [comment]
> Sorry, I meant I ask folks at Microsoft why that's missing :-)

No worries, I would rather (strongly) suggest you roll back to net6 LTS ...

**Comment by terrajobst** [comment]
I was told Canonical is working on it and they are planning to release it around mid-December.

Meanwhile, you can use the Linux build that we provide in our feeds:

https://learn.microsoft.com/en-us/dotnet/core/install/linux-ubuntu#2204

> No worries, I would rather (strongly) suggest you roll back to net6 LTS ...

I really would like to understand why. For .NET Framework I get it because it's a machine wide framework that doesn't support side-by-side installations. If you upgrade for one, you upgrade for everyone. We specifically designed .NET Core such that it's not the case.

It seems that there is a notion of LTS somehow being better/more mature or that STS is somehow unsupported. Considering how often this tool gets updated I don't think there is a problem with picking an STS because when .NET 8 comes around (another LTS) I'm going to use that one too. The result is that this tool always runs on an actively supported versions of .NET.

**Comment by yurikus** [comment]
> I really would like to understand why.
I will try to explain, but first, let me ask you this: what is so crucial that this tool gains from using latest-and-greatest vs LTS that trumps the convenience of availability and ease of install?

Reasons:
- This tool should "just work". What should have been a 15 min shell command spree turned into a multi-day affair.
- Lots and lots of developers working on enterprise software shun bleeding-edge upgrades. I, for once, will never use net7, just like I completely ignored net5. I migrated my stuff to net6 from netcore3.1.  This net7 sdk will just needlessly consume 300MB of VM disk space.
- Stability is important just as implicit understanding that a dependency is likely available for the system you want to use this on. Your move to net5 bit me once already when I was on VS2019. There was no need to upgrade from netcore3.1 just like there's no need to upgrade to net7 now.
- Visual Studio 2022 update 17.4 bit me again by uninstalling net6 sdk completely, thank you very much. Now I have to go to all my build boxes and reinstall net6 sdk manually because my global.json pins it so. 
- There was a time when Razor pages targeting netcore3.1 would generate bad code when built with net6 sdk ... I pin my sdks now.
- many, many more .. I would rather not go into them, at the risk of this sounding like an "old man yelling at cloud" ... but MS over the last few years transitioned into a company that half-a$$es things.

**Comment by terrajobst** [comment]
> I will try to explain, but first, let me ask you this: what is so crucial that this tool gains from using latest-and-greatest vs LTS that trumps the convenience of availability and ease of install?

I will admit that this is somewhat selfish on my end. I work on the .NET team, so I'm basically living on cutting edge and I want to dogfood our features. In the context of this tool this would usually involve library- or language features. Most recent example: C# 11's [raw string literals](https://learn.microsoft.com/en-us/dotnet/csharp/whats-new/csharp-11#raw-string-literals).

My background is library development; for libraries it usually makes sense to target an older version of .NET in order to have more reach. As a library dev, it's common to multi-target, i.e. build for multiple version of .NET in order to support the latest features while not sacrificing reach. This comes, of course, with some amount of complexity for testing and building.

For app development this kind of thinking feels overly complicated. It makes more sense to me to say that this tool requires the latest version of .NET which anyone can install. Well, until recently I naively assumed that when we release it's also available for most Linux distros, which I just learned isn't the case. I should add that I'm mostly on Windows and Mac and for those platforms we (Microsoft) release the builds for.

I guess I'll need to think about this and reconsider.

Would you mind filing a separate issue, asking to make this tool only use .NET LTS releases?
